### PR TITLE
Make all the valued containers subclass `ValueWidget`

### LINKED ISSUE #372: All value-like Container widgets should inherit from ValueWidget
see https://forum.image.sc/t/using-layer-properties-to-pass-variables/63342/6

### PR DESCRIPTION
**Pull request by hanjinliu**
Closes #372 #661 

Now this works:

``` python
from magicgui.widgets import FileEdit, PushButton
from magicgui.widgets.bases import ValueWidget

assert isinstance(PushButton(), ValueWidget)
assert isinstance(FileEdit(), ValueWidget)
```

I had to refactor more than I first thought. The major problem was that `ValueWidget` had `ValueWidgetProtocol` before, which is not compatible with container-like widgets (e.g. there's no `_mgui_get_value` for `FileEdit`). In this PR, I made `ValueWidget` more abstract: it only implements the basic interface for getting/setting values, thus independent of backends. `PrimitiveValueWidget` is the class that require backends, which is identical to the former `ValueWidget`. Besides, I introduced `_BaseContainerWidget` for `ValuedContainerWidget` because many methods of `ContainerWidget` is not publicly needed for value widgets (e.g. we never use `insert` for `FileEdit`).

Inheritance map is now like below.

```
Widget ----------------> ValueWidget --> PrimitiveValueWidget --> Label, LineEdit, Image etc.
   |                        |
   v                        v
_BaseContainerWidget --> ValuedContainerWidget -----------------> FileEdit, RangeEdit, ListEdit etc.
   |
   v
ContainerWidget ------------------------------------------------> Container
```

**Notes:**
- `EmptyWidget` is now a `ValuedContainerWidget ` because it's simply an empty container. Backend implementation of `EmptyWidget` is no longer needed.
- `ValueWidget` now inherits `ABC` because abstractmethod `get_value` and `set_value` are needed. This means if one made a Qt widget and magicgui interface like
  ``` python
  class QMyWidget(QBaseValueWidget): ...

  class MyWidget(ValueWidget):
      def __init__(self, **kwargs):
          kwargs["widget_type"] = QMyWidget
          super().__init__(**kwargs)
  ```
  then it fails with TypeError due to undefined abstract methods.

Please let me know what you think.

### CODE REVIEW

**Comment by tlambert03** [comment]
this looks like a great start @hanjinliu, the one thing I'm not thrilled about is the changing of the meaning of `ValueWidget` to `PrimitiveValueWidget`... it's a breaking change to expect everyone to now inherit from `PrimitiveValueWidget`, and as you can see it breaks your own magic-class tests here.  I'd rather use a shared base class and have it not be the case that `isinstance(TupleWidget(), ValueWidget)` than to rename all ValueWidgets

**Comment by hanjinliu** [comment]
That makes sense. Keeping `ValueWidget` in the same state is definitely safer.
The magic-class tests failed by the isinstance check of ValueWidget but I think this should be fixed on my side (this is due to the update in `EmpytWidget`).
The recent breaking change in `griffe` affects the docs test.

**Comment by tlambert03** [comment]
sorry that this has sat so long @hanjinliu.  would you mind resolving conflicts now that TypeMap is in?

**Comment by tlambert03** [comment]
docs are not building correctly anymore.  I think it may require `magicgui.widgets.bases.BaseValueWidget` to be added to the autosummary in docs/api/widgets/bases.md  Please also check whether the mermaid diagram in that document is still correct after this change, new things may need to be added and the connections may need to be changed

**Comment by hanjinliu** [comment]
Thank you for your help! I found that after the implementation of `TypeMap`, functions that refer to the global type map are not very informative (please look at the API reference of `magicgui.type_map.get_widget_class` in the latest docs for instance). It'll be better to have some links pointing to the `TypeMap` method like `(see [TypeMap.get_widget_class](...))`, but we need additional hooks to this because these lines are built by the pre-defined autoref hook.

**Review by tlambert03 — APPROVED** [review]
thanks @hanjinliu!

**Pull request merged**
