### PR TITLE
feat: add guiclass decorator

### PR DESCRIPTION
**Pull request by tlambert03**
this adds a `guiclass` decorator that combines `psygnal.evented` and `dataclasses.dataclass` as well as a descriptor method for building a widget, as a one-stop-shop for easily creating a dataclass that can create a gui with two-way communication with the underlying object.  It also implements @brisvag's suggestion for the `@button` decorator

as with #475 ... this is all still private and internally experimental

see test for example ... which looks like this:

```python
from magicgui._guiclass import button, guiclass

@guiclass
class Foo:
    a: int = 1
    b: str = "bar"

    @button
    def func(self):
        print(self)

foo = Foo()
foo.gui.show()
```

Screen Shot 2022-11-12 at 9 59 52 PM

### CODE REVIEW

**Comment by brisvag** [comment]
I *love* this, and will be an avid user :) I assume it's intended to also allow keywords for extra customizability the same as with functions?

**Comment by tlambert03** [comment]
All widget specific customizations  should come either in Annotated type annotations, or in a data classes.field() metadata entry.

I'm still thinking about where the container level config (like layout, etc) should go

**Comment by brisvag** [comment]
I see; I like the move to annotations only, I often found it counterintuitive (especially to explain) whether something was supposed to be in the annotation or in the kwarg. So you mean something like:

```python
from magicgui._guiclass import button, guiclass
from dataclasses import field

@guiclass
class Foo:
    a: int = field(widget_type='Slider', ...)
    b: str = "bar"

    @button
    def func(self):
        print(self)

foo = Foo()
foo.gui.show()
```

**Comment by tlambert03** [comment]
yeah, something like that (though note that since you're using `dataclasses.field` it would need to be `field(metadata=dict(widget='Slider'))`

More generally though, the goal here is to support _any_ sort of dataclass (pydantic, attrs, dataclasses) etc...  have a look through [this test](https://github.com/pyapp-kit/magicgui/blob/main/tests/test_ui_field.py) to see all the patterns that we can build widgets from.

So really here, the key bit about `guiclass` is just adding a descriptor object (called `gui` by default) that builds a widget:

```python
class GuiBuilder:
    def __get__(self, instance, owner):
        wdg = build_widget(instance or owner)
        if instance:
            # this part assumes we have an evented instance
            bind_gui_to_instance(wdg, instance)
        return wdg

@evented
@dataclass
class MyClass:
    x: int

    gui = GuiBuilder()
```

and so, the widget-level control can come in so many different ways:

dataclasses
```python
@dataclass
class Foo:
    c: float = field(default=0.0, metadata={"widget": "FloatSlider", "maximum": 100})
```

attrs
```python
import attrs

@attrs.define
class Foo:
    c: float = attrs.field(default=0.0, metadata={"widget": "FloatSlider", "maximum": 100})
```

pydantic
```python
class Foo(pydantic.BaseModel):
    c: float = pydantic.Field(0, widget="FloatSlider", le=100)
```

[annotated_types](https://github.com/annotated-types/annotated-types)
```python
from magicgui.schema import UiField

@dataclass
class Foo:
    c: Annotated[float, UiField(widget='Slider', maximum=100)] = 0

# or

from annotated_types import Le
@dataclass
class Foo:
    c: Annotated[float, Le(100)] = 0
```

so the magicgui-specific part is really quite "light" here.  just accepting any form of dataclass and building a widget.  and then, optionally offering a `.gui` descriptor to add that capability to a class

**Comment by tlambert03** [comment]
This will go through more iterations before it becomes public, but I'm going to merge it as is to play with it some more.  Will probably release a long-lived rc soon

**Pull request merged**
